Prep for doing snapshot releases (vYYYY.MM), building from git sources yields vYYYY.MM.DD version numbers.

diff --git a/scripts/makesrcdist b/scripts/makesrcdist
--- a/scripts/makesrcdist
+++ b/scripts/makesrcdist
@@ -2,14 +2,51 @@
 #
 # makesrcdist - make a source distribution of the IPP sample code.
 #
+# Usage:
+#
+#    scripts/makesrcdist [YYYY.DD]
+#
 
-if test $# != 1; then
-	echo "Usage: ./makesrcdist version"
-	exit 1
+# Make sure we are running in the right directory...
+if test ! -f scripts/makesrcdist; then
+    echo "Run this script from the top-level source directory, e.g.:"
+    echo ""
+    echo "    scripts/makesrcdist $*"
+    echo ""
+    exit 1
 fi
 
-version=$1
+# See if we have local changes (other than this script...)
+if (git status | grep -v makesrcdist | grep -q modified:); then
+    echo Local changes remain:
+    git status | grep modified:
+    exit 1
+fi
 
+# Get the source version...
+if test $# = 1; then
+    version="$(date '+%Y.%m')"
+elif test $# = 2; then
+    version="$1"
+else
+    echo "Usage: ./makesrcdist version"
+    exit 1
+fi
+
+# Get the previous release...
+previous="$(git tag | sort -r | head -1)"
+if test "$previous" = ""; then
+    changes="1"
+else
+    changes="$(git log --oneline $previous...HEAD | wc -l)"
+fi
+
+if test "$changes" = "0"; then
+    echo "No changes since v$previous, aborting."
+    exit 0
+fi
+
+# Create the tag for this release...
 echo Creating tag for release...
 git tag -m "Tag $version" v$version
 git push origin v$version
@@ -20,9 +57,27 @@ mkdir -p .tmp/ippsample-$version
 git archive HEAD | (cd .tmp/ippsample-$version; tar xf -)
 
 for sm in libcups pdfio; do
-	(cd $sm; git archive --prefix=$sm/ HEAD) | (cd .tmp/ippsample-$version; tar xf -)
+    (cd $sm; git archive --prefix=$sm/ HEAD) | (cd .tmp/ippsample-$version; tar xf -)
 done
 
+# Update the configure script...
+sed -e "/^PACKAGE_/s/YYYY.DD/$version/g" < configure > .tmp/ippsample-$version/configure
+chmod +x .tmp/ippsample-$version/configure
+
+# Create the changelog...
+echo "IPP Sample Code v$version" > .tmp/ippsample-$version/CHANGES.md
+echo "========================" >> .tmp/ippsample-$version/CHANGES.md
+echo "" >> .tmp/ippsample-$version/CHANGES.md
+echo "This is a non-production snapshot release of the IPP sample code." >> .tmp/ippsample-$version/CHANGES.md
+
+if test "$previous" != ""; then
+    echo ""  >> .tmp/ippsample-$version/CHANGES.md
+    echo "Changes include:"  >> .tmp/ippsample-$version/CHANGES.md
+    echo ""  >> .tmp/ippsample-$version/CHANGES.md
+    git log --oneline $previous...HEAD | awk '{print "-", $0}' >> .tmp/ippsample-$version/CHANGES.md
+fi
+
+# Create the archives...
 echo Creating ippsample-$version.tar.gz...
 (cd .tmp; tar czf ../ippsample-$version.tar.gz ippsample-$version)
 gpg --detach-sign ippsample-$version.tar.gz
@@ -32,5 +87,6 @@ rm -f ippsample-$version.zip
 (cd .tmp; zip -rq9 ../ippsample-$version.zip ippsample-$version)
 gpg --detach-sign ippsample-$version.zip
 
+# Cleanup...
 echo Cleaning up...
 rm -rf .tmp
